# Generated by Django 3.2.11 on 2022-02-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20220207_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentstatus',
            options={'verbose_name_plural': 'statuses'},
        ),
        migrations.AddField(
            model_name='appointmentstatus',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.userprofile'),
        ),
    ]
