# Generated by Django 3.2.11 on 2022-02-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20220207_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentstatus',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.userprofile'),
        ),
    ]
