# Generated by Django 3.2.11 on 2022-02-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_appointmentstatus_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.appointmentstatus'),
        ),
    ]
